from typing import NamedTuple

class Condition(NamedTuple):
    description: str
    icon: tuple[str, ...]

ICONS: dict[str, tuple[str, ...]] = {
    "clear": (
        "[yellow]   \\   /   [/yellow]",
        "[yellow]    .-.    [/yellow]",
        "[yellow] — (   ) — [/yellow]",
        "[yellow]    `-'    [/yellow]",
        "[yellow]   /   \\   [/yellow]",
    ),
    "partly_cloudy": (
        "[yellow]   \\  /    [/yellow]",
        "[yellow] _ /\"\"[/yellow][white].-.  [/white]",
        "[yellow]   \\_[/yellow][white](   ).[/white]",
        "[yellow]  /[/yellow][white](___(__)[/white]",
        "           ",
    ),
    "cloudy": (
        "           ",
        "[white]    .--.   [/white]",
        "[white] .-(    ). [/white]",
        "[white](___.__)__)[/white]",
        "           ",
    ),
    "light_rain": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[blue]   ' ' ' ' [/blue]",
        "[blue]  ' ' ' '  [/blue]",
    ),
    "moderate_rain": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[blue]  ‚‘‚‘‚‘‚‘ [/blue]",
        "[blue]  ‚’‚’‚’‚’ [/blue]",
    ),
    "heavy_rain": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[blue]  //////// [/blue]",
        "[blue] ////////  [/blue]",
    ),
    "thunderstorm": (
           "[white]    .--.   [/white]",
           "[white] .-(    ). [/white]",
           "[white](___.__)__)[/white]",
           "[blue]//[/blue][yellow]⚡[/yellow][blue]///[/blue][yellow]⚡[/yellow][blue]//[/blue]",
           "[blue]//[/blue][yellow]⚡[/yellow][blue]///[/blue][yellow]⚡[/yellow][blue]//[/blue]",
    ),
    "thunderstorm_without_precipitation": (
           "[white]    .--.   [/white]",
           "[white] .-(    ). [/white]",
           "[white](___.__)__)[/white]",
           "[yellow]  ⚡   ⚡  [/yellow]",
           "[yellow]  ⚡   ⚡  [/yellow]",
    ),
    "funnel_cloud": (
           "[white]    .--.   [/white]",
           "[white] .-(    ). [/white]",
           "[white](___.__)__)[/white]",
           "[white]    \\  /  [/white]",
           "[white]     \\/   [/white]",
    ),
    "fog": (
        "[white]_ - _ - _ -[/white]",
        "[white] _ - _ - _ [/white]",
        "[white]_ - _ - _ -[/white]",
        "[white] _ - _ - _ [/white]",
        "[white]_ - _ - _ -[/white]",
    ),
    "light_snow": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[cyan]   *  *  * [/cyan]",
        "[cyan]  *  *  *  [/cyan]",
    ),
    "moderate_snow": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[cyan]  * * * *  [/cyan]",
        "[cyan] * * * *   [/cyan]",
    ),
    "heavy_snow": (
    "[white]    .--.   [/white]",
    "[white] .-(    ). [/white]",
    "[white](___.__)__)[/white]",
    "[cyan] * * * * * [/cyan]",
    "[cyan]* * * * * *[/cyan]",
    ),
    "hail": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[cyan]   o o o o [/cyan]",
        "[cyan]  o o o o  [/cyan]",
    ),
    "sleet": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[cyan]   * o * o [/cyan]",
        "[cyan]  o * o *  [/cyan]",
    ),
    "light_rain_and_snow": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[cyan]   * ' * ' [/cyan]",
        "[cyan]  ' * ' *  [/cyan]",
    ),
    "moderate_rain_and_snow": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[cyan]  ',*',*',*[/cyan]",
        "[cyan]  *',*',*' [/cyan]",
    ),
    "heavy_rain_and_snow": (
        "[white]    .-.    [/white]",
        "[white]   (   ).  [/white]",
        "[white]  (___(__) [/white]",
        "[cyan]  *//*//*/*[/cyan]",
        "[cyan] //*//*//* [/cyan]",
    ),
    "unknown": (
        "[white]   #####   [/white]",
        "[white]  #     #  [/white]",
        "[white]       #   [/white]",
        "[white]     #     [/white]",
        "[white]     #     [/white]",
    )
}
    
CONDITIONS = {
    "type_1": Condition("Blowing or Drifting Snow", ICONS["moderate_snow"]),
    "type_2": Condition("Drizzle", ICONS["light_rain"]),
    "type_3": Condition("Heavy Drizzle", ICONS["light_rain"]),
    "type_4": Condition("Light Drizzle", ICONS["light_rain"]),
    "type_5": Condition("Heavy Drizzle/Rain", ICONS["moderate_rain"]),
    "type_6": Condition("Light Drizzle/Rain", ICONS["light_rain"]),
    "type_7": Condition("Dust storm", ICONS["fog"]),
    "type_8": Condition("Fog", ICONS["fog"]),
    "type_9": Condition("Freezing Drizzle/Freezing Rain", ICONS["moderate_rain"]),
    "type_10": Condition("Heavy Freezing Drizzle/Freezing Rain", ICONS["moderate_rain"]),
    "type_11": Condition("Light Freezing Drizzle/Freezing Rain", ICONS["light_rain"]),
    "type_12": Condition("Freezing Fog", ICONS["fog"]),
    "type_13": Condition("Heavy Freezing Rain", ICONS["heavy_rain"]),
    "type_14": Condition("Light Freezing Rain", ICONS["light_rain"]),
    "type_15": Condition("Funnel Cloud/Tornado", ICONS["funnel_cloud"]),
    "type_16": Condition("Hail Showers", ICONS["hail"]),
    "type_17": Condition("Ice", ICONS["sleet"]),
    "type_18": Condition("Lightning without Thunder", ICONS["thunderstorm"]),
    "type_19": Condition("Mist", ICONS["fog"]),
    "type_20": Condition("Precipitation in Vicinity", ICONS["light_rain"]),
    "type_21": Condition("Rain", ICONS["moderate_rain"]),
    "type_22": Condition("Heavy Rain and Snow", ICONS["heavy_rain_and_snow"]),
    "type_23": Condition("Light Rain and Snow", ICONS["light_rain_and_snow"]),
    "type_24": Condition("Rain Showers", ICONS["moderate_rain"]),
    "type_25": Condition("Heavy Rain", ICONS["heavy_rain"]),
    "type_26": Condition("Light Rain", ICONS["light_rain"]),
    "type_27": Condition("Sky Coverage Decreasing", ICONS["partly_cloudy"]),
    "type_28": Condition("Sky Coverage Increasing", ICONS["partly_cloudy"]),
    "type_29": Condition("Sky Coverage Unchanged", ICONS["partly_cloudy"]),
    "type_30": Condition("Smoke or Haze", ICONS["fog"]),
    "type_31": Condition("Snow", ICONS["moderate_snow"]),
    "type_32": Condition("Snow and Rain Showers", ICONS["moderate_rain_and_snow"]),
    "type_33": Condition("Snow Showers", ICONS["moderate_snow"]),
    "type_34": Condition("Heavy Snow", ICONS["heavy_snow"]),
    "type_35": Condition("Light Snow", ICONS["light_snow"]),
    "type_36": Condition("Squalls", ICONS["thunderstorm"]),
    "type_37": Condition("Thunderstorm", ICONS["thunderstorm"]),
    "type_38": Condition("Thunderstorm Without Precipitation", ICONS["thunderstorm_without_precipitation"]),
    "type_39": Condition("Diamond Dust", ICONS["fog"]),
    "type_40": Condition("Hail", ICONS["hail"]),
    "type_41": Condition("Overcast", ICONS["cloudy"]),
    "type_42": Condition("Partially Cloudy", ICONS["partly_cloudy"]),
    "type_43": Condition("Clear", ICONS["clear"]),
}

    